# Оповещения [/announcement]

## Получить все оповещения [GET /announcement]

+ Response 200 (application/json)
    + Attributes (array[AnnouncementResponse])

# Data Structures

## AnnouncementResponse

+ id: 0 (number)
+ title: `Отключение горячей воды` (string)
+ body: `Отключение горячей воды` (string)
+ date: 2021-12-17T05:28:42.242Z (string)