name: .NET

on:
  pull_request:
    branches: [main]
    types: [closed, opened]

defaults:
  run:
    working-directory: ./Server/Sources

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

  docker:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name:
          Build and push Docker images
        uses: docker/build-push-action@v2.3.0
        with:
          # Build's context is the set of files located in the specified PATH or URL
          context: ./Server/Sources
          # Path to the Dockerfile
          file: ./Server/Docker/.dockerfile
          # List of tags
          tags: somka4docker/spas-dom-server:latest
          # Push is a shorthand for --output=type=registry
          push: true
